# Generated by Django 4.0.2 on 2022-02-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('credits', models.TextField(max_length=80)),
                ('code', models.TextField(max_length=80, unique=True)),
                ('price', models.TextField(max_length=80)),
                ('max', models.TextField(max_length=80)),
            ],
        ),
    ]
