# Generated by Django 4.0.2 on 2022-02-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='id',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.TextField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
