# Generated by Django 4.0.2 on 2022-02-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_remove_voucher_id_alter_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
